Add systemd support

diff --git a/data/cli/cli.sh.erb b/data/cli/cli.sh.erb
--- a/data/cli/cli.sh.erb
+++ b/data/cli/cli.sh.erb
@@ -29,6 +29,7 @@ usage() {
 }
 
 DEFAULT_FILE=$(_p "/etc/default/${APP_NAME}")
+SYSTEMD_DIR=$(_p "/etc/systemd/system")
 
 . ${DEFAULT_FILE}
 
@@ -86,6 +87,8 @@ current_number_of_processes() {
   PROCESS_NAME="$1"
   if [ "${APP_RUNNER_TYPE}" = "upstart" ]; then
     echo $(ls -rv1 $(_p /etc/init/)${APP_NAME}-${PROCESS_NAME}-*.conf 2>/dev/null | head -1 | sed -r 's/.*\-([0-9]+)\.conf/\1/g')
+  elif [ "${APP_RUNNER_TYPE}" = "systemd" ]; then
+    echo $(ls -rv1 $SYSTEMD_DIR/${APP_NAME}-${PROCESS_NAME}-*.service 2>/dev/null | head -1 | sed -r 's/.*\-([0-9]+)\.service/\1/g')
   else
     echo $(ls -rv1 $(_p /etc/init.d/)${APP_NAME}-${PROCESS_NAME}-* 2>/dev/null | head -1 | sed -r 's/.*\-([0-9]+)/\1/g')
   fi
@@ -114,6 +117,8 @@ sysv_enable() {
     $APP_RUNNER_CLI "$name" on
   elif [ "$APP_RUNNER_CLI" = "update-rc.d" ] ; then
     $APP_RUNNER_CLI "$name" defaults
+  elif [ "$APP_RUNNER_CLI" = "systemctl" ] ; then
+    $APP_RUNNER_CLI enable "$name"
   fi
 }
 
@@ -123,6 +128,8 @@ sysv_disable() {
     $APP_RUNNER_CLI "$name" off
   elif [ "$APP_RUNNER_CLI" = "update-rc.d" ] ; then
     $APP_RUNNER_CLI -f "$name" remove
+  elif [ "$APP_RUNNER_CLI" = "systemctl" ] ; then
+    $APP_RUNNER_CLI disable "$name"
   fi
 }
 
@@ -157,6 +164,30 @@ scale_up() {
 
     $APP_RUNNER_CLI start ${APP_NAME}-${PROCESS_NAME} || true
     $APP_RUNNER_CLI start ${APP_NAME} || true
+  elif [ "$APP_RUNNER_TYPE" = "systemd" ]; then
+    local source=$(_p "${APP_HOME}/vendor/pkgr/scaling/systemd")
+    # copy master
+    cp ${source}/${APP_NAME}.service $SYSTEMD_DIR
+    # copy master process
+    cp ${source}/${APP_NAME}-${PROCESS_NAME}.service $SYSTEMD_DIR
+
+    $APP_RUNNER_CLI enable ${APP_NAME}.service || true
+    $APP_RUNNER_CLI enable ${APP_NAME}-${PROCESS_NAME}.service || true
+
+    for i in $(seq ${SCALE_DELTA}); do
+      index=$((${i} + ${CURRENT_SCALE}))
+      PROCESS_ID="${APP_NAME}-${PROCESS_NAME}-${index}"
+      cp ${source}/${APP_NAME}-${PROCESS_NAME}-PROCESS_NUM.service $SYSTEMD_DIR/${PROCESS_ID}.service
+      port=$((${PORT} + ${index} - 1))
+
+      update_port $SYSTEMD_DIR/${PROCESS_ID}.service "${PROCESS_NAME}" $port $index
+
+      $APP_RUNNER_CLI enable "${PROCESS_ID}.service"
+    done
+
+    $APP_RUNNER_CLI daemon-reload
+    $APP_RUNNER_CLI start ${APP_NAME}-${PROCESS_NAME}.service
+    $APP_RUNNER_CLI start ${APP_NAME}.service
   else
     cp $(_p "${APP_HOME}/vendor/pkgr/scaling/sysv/${APP_NAME}") $(_p /etc/init.d/)
     chmod a+x $(_p "/etc/init.d/${APP_NAME}")
@@ -192,8 +223,12 @@ scale_down() {
     PROCESS_ID="${APP_NAME}-${PROCESS_NAME}-${index}"
 
     if [ "${APP_RUNNER_TYPE}" = "upstart" ]; then
-      $APP_RUNNER_CLI stop "${PROCESS_ID}" || /bin/true # dont fail if server stopped differently
+      $APP_RUNNER_CLI stop "${PROCESS_ID}" || true # dont fail if server stopped differently
       rm -f $(_p "/etc/init/${PROCESS_ID}.conf")
+    elif [ "${APP_RUNNER_TYPE}" = "systemd" ]; then
+      $APP_RUNNER_CLI stop "${PROCESS_ID}.service" || true # dont fail if server stopped differently
+      $APP_RUNNER_CLI disable "${PROCESS_ID}.service" || true
+      rm -f $SYSTEMD_DIR/${PROCESS_ID}.service
     else
       $(_p "/etc/init.d/${PROCESS_ID}") stop
       sysv_disable ${PROCESS_ID}
