Allow to run some commands as the APP_USER instead of root

diff --git a/data/cli/cli.sh.erb b/data/cli/cli.sh.erb
--- a/data/cli/cli.sh.erb
+++ b/data/cli/cli.sh.erb
@@ -41,9 +41,9 @@ if [ "$APP_CLI" != "" ] ; then
   exec $APP_HOME/bin/$APP_CLI "$@"
 fi
 
-if [ `id -u` -ne 0 ]; then
-  echo "You must be executing with root privileges to launch commands."
-  echo "Either log in as root, use sudo, or add sudo privileges for running ${APP_NAME} with your user."
+if [ ! -w "$(_p "/etc/${APP_NAME}/conf.d")" ] ; then
+  echo "Error: You must be executing as the user '${APP_USER}' or with root privileges to launch commands."
+  echo "Either log in as '${APP_USER}', root, use sudo, or add sudo privileges for running ${APP_NAME} with your current user."
   exit 1
 fi
 
@@ -52,6 +52,15 @@ fi
 for file in $(_p "/etc/${APP_NAME}/conf.d")/*; do
   if [ -f $file ]; then . $file; fi
 done
+
+# Some actions require root privileges
+ensure_root() {
+  if [ $(id -u) -ne 0 ]; then
+    echo "Error: You must be executing with root privileges to use this command."
+    echo "Either log in as root, use sudo, or add sudo privileges for running ${APP_NAME} with your user."
+    exit 1
+  fi
+}
 
 # Return all the environment variables accessible to the app.
 show_env() {
@@ -260,11 +269,18 @@ while : ; do
       # Do not use su, to avoid creating a new process. Note: chroot version
       # is too old on Ubuntu Lucid, so this will fail. It works on Debian
       # Squeeze though (and later).
-      exec chroot --userspec ${APP_USER}:${APP_GROUP} "/" sh -c "cd $(_p ${APP_HOME}) && $runnable"
+      # Do not chroot if current user is APP_USER.
+      if [ $(id -u) = $(id -u ${APP_USER}) ]; then
+        exec sh -c "cd $(_p ${APP_HOME}) && $runnable"
+      else
+        exec chroot --userspec ${APP_USER}:${APP_GROUP} "/" sh -c "cd $(_p ${APP_HOME}) && $runnable"
+      fi
 
       break ;;
 
     scale)
+      ensure_root
+
       shift
       for arg in "$@"; do
         [ "$arg" = "" ] && usage
@@ -313,10 +329,14 @@ while : ; do
       break;;
 
     configure)
+      ensure_root
+
       configure $@
       break;;
 
     reconfigure)
+      ensure_root
+
       reconfigure $@
       break;;
 
